// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutiS7xdmfg5FbXRfJIsfxd8nYWE3F-UA',
    appId: '1:849404112354:web:cb6085229b7fb33d689dbb',
    messagingSenderId: '849404112354',
    projectId: 'messenger-67501',
    authDomain: 'messenger-67501.firebaseapp.com',
    storageBucket: 'messenger-67501.appspot.com',
    measurementId: 'G-81NJLEKJ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1nz5KEv1LKjWpabBWW_tCVVqnSvY2OLM',
    appId: '1:849404112354:android:39a967b3de1f199d689dbb',
    messagingSenderId: '849404112354',
    projectId: 'messenger-67501',
    storageBucket: 'messenger-67501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwqZM7hMFeJNP523Am6feBd7nsgaJf1Ac',
    appId: '1:849404112354:ios:ed263540c24db5aa689dbb',
    messagingSenderId: '849404112354',
    projectId: 'messenger-67501',
    storageBucket: 'messenger-67501.appspot.com',
    iosBundleId: 'com.classcar200.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwqZM7hMFeJNP523Am6feBd7nsgaJf1Ac',
    appId: '1:849404112354:ios:ed263540c24db5aa689dbb',
    messagingSenderId: '849404112354',
    projectId: 'messenger-67501',
    storageBucket: 'messenger-67501.appspot.com',
    iosBundleId: 'com.classcar200.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCutiS7xdmfg5FbXRfJIsfxd8nYWE3F-UA',
    appId: '1:849404112354:web:f5a302d21314b64e689dbb',
    messagingSenderId: '849404112354',
    projectId: 'messenger-67501',
    authDomain: 'messenger-67501.firebaseapp.com',
    storageBucket: 'messenger-67501.appspot.com',
    measurementId: 'G-7MBZSHHDWV',
  );
}
